version: "3.8"
services:
  ## postgres database
  postgres:
    container_name: postgres_database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sqltester
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - type: volume
        source: flask_postgres_data
        target: /var/lib/postgres/data
    networks:
      - flask_app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  ## flask api
  flask_app:
    container_name: flask_app
    env_file: .dockerenv
    build: ./back-end
    ports:
      - "5000:5000"
    networks:
      - flask_app_network
    volumes:
      - type: bind
        source: ./back-end/src # only going to be bind mounting the code
        target: /code
    command: flask run -h 0.0.0.0
    depends_on:
      - pre-setup
  ## pre-setup
  pre-setup:
    build: ./back-end
    env_file: .dockerenv
    networks:
      - flask_app_network
    command:
      - /bin/bash
      - -c
      - |
        echo "running pre-setup"
        flask db_custom initialize_schema
        flask db upgrade
        flask db_custom seed_question
        flask db_custom seed_secondary_tables
    depends_on:
      postgres:
        condition: service_healthy
  ## front-end
  react-app:
    container_name: react_app
    
    build: 
      context: ./front-end
      args:
        - REACT_APP_HOST=http://localhost:5000
    ports:
      - "9090:80"
    networks:
      - flask_app_network
    
## volumes
volumes:
  flask_postgres_data:
    name: flask_postgres_data
## networks
networks:
  flask_app_network:
    name: flask_app_network
    driver: bridge
        
